POST http://localhost:8090/api/collections/reservation/records
Content-Type: application/json

{
  "customer_name": "John",
  "customer_phone": "0123456789",
  "customer_email": "john@doe.tld",
  "items": [
    "s4j6dg5tpd9mf80"
  ],
  "pickup": "2025-12-29 16:00:00"
}